import { Metadata } from "next";
import Link from "next/link";
import { ShieldCheck, FileText, AlertCircle } from "lucide-react";

export const metadata: Metadata = {
  title: "Terms of Service | WebAudit Pro",
  description: "Terms and conditions for utilizing the WebAudit Pro security scanner platform.",
};

export default function TermsPage() {
  return (
    <div style={{ maxWidth: 860, margin: "0 auto", padding: "60px 24px" }}>
      {/* Header */}
      <div style={{ textAlign: "center", marginBottom: 48 }}>
        <div
          style={{
            width: 48,
            height: 48,
            borderRadius: "50%",
            background: "rgba(0, 163, 255, 0.1)",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            color: "var(--accent-primary)",
            margin: "0 auto 16px",
          }}
        >
          <FileText size={24} />
        </div>
        <h1 style={{ fontSize: "clamp(30px, 4vw, 44px)", fontWeight: 900, marginBottom: 12 }}>
          Terms of <span className="gradient-text">Service</span>
        </h1>
        <p style={{ fontSize: 15, color: "var(--text-secondary)" }}>
          Last modified: May 29, 2026
        </p>
      </div>

      {/* Main Copy */}
      <div className="glass-card" style={{ padding: "40px", display: "flex", flexDirection: "column", gap: 24 }}>
        <section>
          <h2 style={{ fontSize: 18, fontWeight: 700, marginBottom: 12, color: "var(--text-primary)" }}>
            1. Acceptance of Terms
          </h2>
          <p style={{ fontSize: 14, color: "var(--text-secondary)", lineHeight: 1.7 }}>
            By accessing and utilizing WebAudit Pro ("the Platform"), you agree to be bound by these Terms of Service. If you do not agree to all of the terms, you are prohibited from utilizing the Platform or its aggregated security intelligence API feeds.
          </p>
        </section>

        <hr style={{ border: "none", borderTop: "1px solid var(--border-subtle)" }} />

        <section>
          <h2 style={{ fontSize: 18, fontWeight: 700, marginBottom: 12, color: "var(--text-primary)" }}>
            2. Permissible Audit Use Cases & Authorization
          </h2>
          <p style={{ fontSize: 14, color: "var(--text-secondary)", lineHeight: 1.7, marginBottom: 12 }}>
            WebAudit Pro operates strictly as a **passive security assessment utility**. The audits executed do not trigger active exploitation vectors, aggressive payloads, or denial of service scripts.
          </p>
          <div
            style={{
              padding: "16px 20px",
              background: "rgba(255, 180, 171, 0.05)",
              border: "1px solid rgba(255, 180, 171, 0.15)",
              borderRadius: "var(--radius-sm)",
              display: "flex",
              gap: 12,
              alignItems: "flex-start",
            }}
          >
            <AlertCircle size={18} style={{ color: "var(--accent-red)", flexShrink: 0, marginTop: 2 }} />
            <p style={{ fontSize: 13, color: "var(--text-muted)", lineHeight: 1.6 }}>
              <strong>IMPORTANT LEGAL NOTICE:</strong> You represent and warrant that you own, operate, or have explicit written authorization to perform security audits on any target domain submitted to the Platform. Submission of unauthorized third-party URLs may violate regional computer abuse laws.
            </p>
          </div>
        </section>

        <hr style={{ border: "none", borderTop: "1px solid var(--border-subtle)" }} />

        <section>
          <h2 style={{ fontSize: 18, fontWeight: 700, marginBottom: 12, color: "var(--text-primary)" }}>
            3. Disclaimer of Liability & Accuracy
          </h2>
          <p style={{ fontSize: 14, color: "var(--text-secondary)", lineHeight: 1.7 }}>
            All reports, scores, findings, CVSS calculations, and CVE mappings generated by the Platform are provided on an "as-is" and "as-available" basis. We aggregate passive data from external open-source engines and make no guarantees regarding accuracy, integrity, or completeness of the findings. Submitting audits does not replace formal, human-led penetration testing services.
          </p>
        </section>

        <hr style={{ border: "none", borderTop: "1px solid var(--border-subtle)" }} />

        <section>
          <h2 style={{ fontSize: 18, fontWeight: 700, marginBottom: 12, color: "var(--text-primary)" }}>
            4. Abuse, Rate Limits & Paywall Restraints
          </h2>
          <p style={{ fontSize: 14, color: "var(--text-secondary)", lineHeight: 1.7 }}>
            We reserve the right to throttle, block, or permanently suspend user accounts or IP addresses that make abusive demands, automated scraping scripts, or repetitive requests targeted to deplete our API key free quotas. Free tier users are capped at predefined daily limits, with expanded historical views gated behind the platform's standard SaaS payment portals.
          </p>
        </section>

        <hr style={{ border: "none", borderTop: "1px solid var(--border-subtle)" }} />

        <section>
          <h2 style={{ fontSize: 18, fontWeight: 700, marginBottom: 12, color: "var(--text-primary)" }}>
            5. MIT Open-Source & Copyright
          </h2>
          <p style={{ fontSize: 14, color: "var(--text-secondary)", lineHeight: 1.7 }}>
            The WebAudit Pro application core is open-source software licensed under the terms of the MIT License. You are free to modify, fork, distribute, and integrate the codebase in private or commercial software environments, subject to the inclusion of the original license notice.
          </p>
        </section>
      </div>

      {/* Footer link */}
      <div style={{ textAlign: "center", marginTop: 32 }}>
        <Link href="/" style={{ color: "var(--text-muted)", fontSize: 13, textDecoration: "none", display: "inline-flex", alignItems: "center", gap: 6 }}>
          <ShieldCheck size={14} /> Back to Audit Portal
        </Link>
      </div>
    </div>
  );
}
